# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7iABRfIWux7d963eV6EWh5b0B6TVvgz
"""

import pandas as pd
shoh={
    "fish":[ "Abduhoshimov Shahriyor","Aliyev abdulvosid","halilov durbek","zuluov umidjon","saidov aziz","oribjonova mubina","saidova aziza","halilova sevinch","aliyeva muslima","ummataliyeva sevara"  ],
    "yoshi":[ "19","19","18","13","8","18","9","18","21","20"   ],
    "maktabi":[  "5-maktab","3-maktab","7-maktab","45-maktab","73-maktab","35-maktab","2-maktab","46-maktab","78-maktab","6-maktab"   ],
    "jinsi":[ "erkak","erkak","erkak","erkak","erkak","ayol","ayol","ayol","ayol","ayol"     ],
    "manzili":[  "andijon","andijon","fargona","buxoro","namangan","toshkent","samarqand","andijon","fargona","namangan" ]

}
malumot=pd.DataFrame(shoh)
print(malumot)

filtr=malumot[(malumot['jinsi']=='ayol') & (malumot['yoshi']>'15')]
print(filtr)

filtr=malumot[(malumot['yoshi']<'15')]
print(filtr)